import { StyleSheet } from "react-native";

const createCommunityStyles = (isDarkMode = false) => {
  const palette = isDarkMode
    ? {
        container: "#111111",
        header: "#1C1C1C",
        input: "#F3F3F3",
        card: "#1E1E1E",
        border: "#2B2B2B",
        chip: "#2A2A2A",
        text: "#F3F3F3",
        subText: "#A8A8A8",
        comment: "#262626",
        commentInput: "#2A2A2A",
        pollCard: "#2A1E22",
        pollBorder: "#4A3139",
        pollOption: "#242424",
      }
    : {
        container: "#f2f2f2",
        header: "#ffffff",
        input: "#111111",
        card: "#ffffff",
        border: "#ececec",
        chip: "#e5e5e5",
        text: "#222222",
        subText: "#777777",
        comment: "#f7f7f7",
        commentInput: "#f2f2f2",
        pollCard: "#fff6f9",
        pollBorder: "#ffd0de",
        pollOption: "#ffffff",
      };

  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: palette.container,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: palette.header,
    borderRadius: 20,
    margin: 10,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: palette.input,
  },
  headerIcons: {
    flexDirection: "row",
    gap: 12,
  },
  carouselContainer: {
    width: "100%",
    height: 230,
    marginTop: 5,
  },
  carouselImage: {
    width: "100%",
    height: "100%",
  },
  dots: {
    flexDirection: "row",
    position: "absolute",
    bottom: 12,
    alignSelf: "center",
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 5,
    backgroundColor: "#ccc",
    marginHorizontal: 4,
  },
  activeDot: {
    backgroundColor: "white",
  },
  chipRow: {
    flexDirection: "row",
    marginTop: 15,
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  chip: {
    backgroundColor: palette.chip,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    marginRight: 10,
  },
  activeChip: {
    backgroundColor: "#ff4d73",
  },
  chipText: {
    fontSize: 13,
    color: palette.text,
  },
  activeChipText: {
    color: "white",
    fontSize: 13,
  },
  feedSpace: {
    height: 400,
  },
  feedLoadingWrap: {
    paddingVertical: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  feedList: {
    paddingHorizontal: 10,
    paddingBottom: 24,
    gap: 12,
  },
  feedContentContainer: {
    paddingBottom: 24,
  },
  feedItemSeparator: {
    height: 12,
  },
  feedCard: {
    backgroundColor: palette.card,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: palette.border,
  },
  feedHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  avatarWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    overflow: "hidden",
    marginRight: 8,
  },
  avatar: {
    width: "100%",
    height: "100%",
  },
  avatarPlaceholder: {
    width: "100%",
    height: "100%",
    borderRadius: 16,
    backgroundColor: isDarkMode ? "#2C2C2C" : "#efefef",
    alignItems: "center",
    justifyContent: "center",
  },
  feedHeaderText: {
    flex: 1,
  },
  authorName: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.text,
  },
  postMeta: {
    fontSize: 11,
    color: palette.subText,
    marginTop: 1,
  },
  postCaption: {
    fontSize: 14,
    color: palette.text,
    marginBottom: 8,
    lineHeight: 20,
  },
  postImage: {
    width: "100%",
    height: 220,
    borderRadius: 12,
    backgroundColor: isDarkMode ? "#232323" : "#f4f4f4",
    marginBottom: 10,
  },
  feedActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 2,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  actionText: {
    fontSize: 12,
    color: palette.subText,
    fontWeight: "600",
  },
  commentsSection: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    paddingTop: 8,
    gap: 6,
  },
  commentRow: {
    backgroundColor: palette.comment,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  commentAuthor: {
    fontSize: 11,
    color: palette.subText,
    fontWeight: "700",
    marginBottom: 2,
  },
  commentText: {
    fontSize: 13,
    color: palette.text,
  },
  commentComposer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  commentInput: {
    flex: 1,
    backgroundColor: palette.commentInput,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: palette.text,
  },
  commentSend: {
    color: "#ff4d73",
    fontWeight: "700",
    fontSize: 13,
    paddingHorizontal: 4,
  },
  pollCard: {
    marginBottom: 8,
    backgroundColor: palette.pollCard,
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: palette.pollBorder,
    gap: 8,
  },
  pollQuestion: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.text,
  },
  pollOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: palette.pollOption,
    borderWidth: 1,
    borderColor: palette.pollBorder,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  pollOptionActive: {
    backgroundColor: "#ff4d73",
    borderColor: "#ff4d73",
  },
  pollOptionText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "600",
  },
  pollOptionTextActive: {
    color: "#fff",
  },
  pollVotes: {
    color: palette.subText,
    fontSize: 12,
    fontWeight: "700",
  },
  emptyStateCard: {
    marginHorizontal: 10,
    marginTop: 10,
    backgroundColor: palette.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
    paddingVertical: 28,
    paddingHorizontal: 14,
    gap: 6,
  },
  emptyStateTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.text,
  },
  emptyStateText: {
    fontSize: 13,
    color: palette.subText,
    textAlign: "center",
  },
  loadMoreWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
  },
  loadMoreText: {
    color: palette.subText,
    fontSize: 12,
    fontWeight: "600",
  },
  endOfFeedText: {
    textAlign: "center",
    color: palette.subText,
    fontSize: 12,
    paddingVertical: 12,
  },
  floatingButton: {
    position: "absolute",
    bottom: 35,
    alignSelf: "center",
    backgroundColor: "#ff4d73",
    width: 65,
    height: 65,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: 70,
    backgroundColor: "black",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  overlay: {
    position: "absolute",
    bottom: 20,
    left: 20,
  },
  overlayTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
  },
  overlaySub: {
    color: "white",
    fontSize: 13,
    marginTop: 4,
  },
});
};

export default createCommunityStyles;