import { StyleSheet } from "react-native";

const createCommunityStyles = (isDarkMode = false) => {
  const palette = isDarkMode
    ? {
        container: "#0F0F0F",
        header: "#1A1A1A",
        inputText: "#F0F0F0",
        card: "#1A1A1A",
        cardBorder: "#2A2A2A",
        chip: "#2A2A2A",
        text: "#F0F0F0",
        subText: "#888",
        commentBg: "#222",
        commentInput: "#252525",
        divider: "#222",
        badgeBg: "#2A2A2A",
        badgeText: "#999",
      }
    : {
        container: "#F5F5F5",
        header: "#FFFFFF",
        inputText: "#111",
        card: "#FFFFFF",
        cardBorder: "#EBEBEB",
        chip: "#fff",
        text: "#111",
        subText: "#888",
        commentBg: "#F7F7F7",
        commentInput: "#F0F0F0",
        divider: "#F0F0F0",
        badgeBg: "#F0F0F0",
        badgeText: "#888",
      };

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.container,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingVertical: 6,
      backgroundColor: palette.header,
      marginHorizontal: 12,
      marginTop: 8,
      marginBottom: 4,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.cardBorder,
    },
    topHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 12,
    },
    topHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    searchInput: {
      flex: 1,
      marginLeft: 8,
      fontSize: 12,
      color: palette.inputText,
      paddingVertical: 1,
    },
    headerIcons: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
    },
    notifBtn: {
      position: "relative",
    },
    notifBadge: {
      position: "absolute",
      top: -5,
      right: -5,
      backgroundColor: "#ff4d73",
      borderRadius: 9,
      minWidth: 17,
      height: 17,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 3,
    },
    notifBadgeText: {
      color: "#fff",
      fontSize: 9,
      fontWeight: "800",
    },
    chipHeaderWrap: {
      paddingBottom: 7,
      position: "relative",
      overflow: "visible",
      zIndex: 30,
      elevation: 30,
    },
    chipRow: {
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 12,
      gap: 8,
      flexDirection: "row",
      alignItems: "flex-start",
      overflow: "visible",
    },
    chipItemWrap: {
      alignItems: "flex-start",
      position: "relative",
      overflow: "visible",
      zIndex: 40,
      elevation: 40,
    },
    chip: {
      backgroundColor: palette.chip,
      paddingVertical: 7,
      paddingHorizontal: 16,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: isDarkMode ? "#3A3A3A" : "#EBEBEB",
    },
    activeChip: {
      backgroundColor: "#ff4d73",
    },
    chipText: {
      fontSize: 13,
      color: isDarkMode ? "#C9C9C9" : palette.text,
      fontWeight: "500",
    },
    activeChipText: {
      color: "#fff",
      fontSize: 13,
      fontWeight: "600",
    },
    styledChipContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    styledDropdownMenu: {
      position: "absolute",
      top: 40,
      left: 0,
      minWidth: 180,
      backgroundColor: palette.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.cardBorder,
      overflow: "hidden",
      zIndex: 60,
      elevation: 60,
    },
    dropdownBackdrop: {
      flex: 1,
    },
    styledDropdownPortal: {
      position: "absolute",
      backgroundColor: palette.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.cardBorder,
      overflow: "hidden",
      zIndex: 120,
      elevation: 120,
    },
    styledDropdownOption: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: palette.divider,
    },
    styledDropdownOptionActive: {
      backgroundColor: isDarkMode ? "#2A151D" : "#FFE7EE",
    },
    styledDropdownOptionText: {
      color: palette.text,
      fontSize: 13,
      fontWeight: "500",
    },
    styledDropdownOptionTextActive: {
      color: "#ff4d73",
      fontWeight: "700",
    },
    feedContentContainer: {
      paddingBottom: 32,
    },
    postBlock: {
      marginBottom: 10,
      zIndex: 1,
      elevation: 1,
    },
    feedCard: {
      backgroundColor: palette.card,
      marginHorizontal: 20,
      marginBottom: 0,
      borderRadius: 18,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: palette.cardBorder,
    },
    feedHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 8,
    },
    feedHeaderText: {
      flex: 1,
      marginLeft: 10,
    },
    feedHeaderTop: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    authorName: {
      fontSize: 13,
      fontWeight: "500",
      color: palette.text,
      letterSpacing: -0.2,
    },
    postTypeBadge: {
      backgroundColor: palette.badgeBg,
      borderRadius: 6,
      paddingHorizontal: 7,
      paddingVertical: 2,
    },
    postTypeBadgeText: {
      fontSize: 10,
      fontWeight: "600",
      color: palette.badgeText,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    postMeta: {
      fontSize: 11,
      color: palette.subText,
      marginTop: 1,
    },
    followPillBtn: {
      backgroundColor: "#ff4d73",
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 5,
      marginLeft: 8,
    },
    followPillBtnText: {
      color: "#fff",
      fontSize: 13,
      fontWeight: "600",
    },
    postImageWrap: {
      width: "100%",
      backgroundColor: isDarkMode ? "#1a1a1a" : "#f0f0f0",
      borderRadius: 14,
      overflow: "hidden",
      minHeight: 420,
    },
    postImage: {
      width: "100%",
      height: 440,
    },
    postCaption: {
      fontSize: 13,
      color: palette.text,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 2,
      lineHeight: 19,
    },
    feedActions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      marginHorizontal: 20,
      paddingHorizontal: 2,
      paddingTop: 6,
      paddingBottom: 8,
    },
    feedActionsLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    actionButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    actionText: {
      fontSize: 13,
      color: palette.text,
      fontWeight: "600",
    },
    commentsSection: {
      marginHorizontal: 20,
      marginTop: 2,
      backgroundColor: palette.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.cardBorder,
      paddingHorizontal: 14,
      paddingVertical: 10,
      gap: 8,
    },
    commentRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
    },
    commentBubble: {
      flex: 1,
      backgroundColor: palette.commentBg,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    commentAuthor: {
      fontSize: 11,
      fontWeight: "700",
      color: palette.text,
      marginBottom: 2,
    },
    commentText: {
      fontSize: 13,
      color: palette.text,
      lineHeight: 17,
    },
    commentComposer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginTop: 4,
    },
    commentInput: {
      flex: 1,
      backgroundColor: palette.commentInput,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 9,
      fontSize: 13,
      color: palette.text,
    },
    commentSendBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: isDarkMode ? "#2A2A2A" : "#F5F5F5",
      alignItems: "center",
      justifyContent: "center",
    },
    userSearchCard: {
      marginHorizontal: 12,
      marginBottom: 8,
      backgroundColor: palette.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.cardBorder,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 10,
    },
    userSearchHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    userSearchTitle: {
      color: palette.text,
      fontSize: 13,
      fontWeight: "700",
    },
    userSearchEmptyText: {
      color: palette.subText,
      fontSize: 13,
    },
    userRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    userRowLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      gap: 10,
    },
    userMetaWrap: {
      flex: 1,
    },
    userNameText: {
      color: palette.text,
      fontSize: 13,
      fontWeight: "700",
    },
    userCountsText: {
      color: palette.subText,
      fontSize: 11,
      marginTop: 1,
    },
    followButton: {
      borderRadius: 20,
      backgroundColor: "#ff4d73",
      paddingHorizontal: 16,
      paddingVertical: 7,
    },
    followingButton: {
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: palette.cardBorder,
    },
    followButtonText: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "700",
    },
    followingButtonText: {
      color: palette.subText,
    },
    feedLoadingWrap: {
      paddingVertical: 60,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyStateCard: {
      marginHorizontal: 12,
      marginTop: 8,
      backgroundColor: palette.card,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: palette.cardBorder,
      alignItems: "center",
      paddingVertical: 40,
      paddingHorizontal: 24,
      gap: 8,
    },
    emptyStateTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: palette.text,
      textAlign: "center",
    },
    emptyStateText: {
      fontSize: 13,
      color: palette.subText,
      textAlign: "center",
      lineHeight: 18,
    },
    loadMoreWrap: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 16,
    },
    endOfFeedText: {
      textAlign: "center",
      color: palette.subText,
      fontSize: 12,
      paddingVertical: 16,
    },
    notifOverlay: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    notifSheet: {
      backgroundColor: palette.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingBottom: 44,
      paddingTop: 14,
      maxHeight: "78%",
    },
    notifSheetHandle: {
      width: 38,
      height: 4,
      borderRadius: 2,
      backgroundColor: palette.cardBorder,
      alignSelf: "center",
      marginBottom: 18,
    },
    notifSheetTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: palette.text,
      marginBottom: 16,
      letterSpacing: -0.3,
    },
    notifEmptyWrap: {
      alignItems: "center",
      paddingVertical: 40,
      gap: 10,
    },
    notifEmpty: {
      color: palette.subText,
      fontSize: 14,
      textAlign: "center",
    },
    notifRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: palette.divider,
    },
    notifRowUnread: {
      backgroundColor: isDarkMode ? "#1a0e12" : "#fff5f7",
      marginHorizontal: -20,
      paddingHorizontal: 20,
    },
    notifAvatarWrap: {
      position: "relative",
    },
    notifAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
    },
    notifAvatarPlaceholder: {
      backgroundColor: isDarkMode ? "#2A2A2A" : "#F5F5F5",
      alignItems: "center",
      justifyContent: "center",
    },
    notifTypeIcon: {
      position: "absolute",
      bottom: -2,
      right: -2,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: "#ff4d73",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: palette.card,
    },
    notifTextWrap: {
      flex: 1,
    },
    notifMessage: {
      fontSize: 13,
      color: palette.text,
      fontWeight: "500",
      lineHeight: 18,
    },
    notifTime: {
      fontSize: 11,
      color: palette.subText,
      marginTop: 2,
    },
    notifDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: "#ff4d73",
    },
  });
};

export default createCommunityStyles;

