const ALLOWED_GARMENT_SUBCATEGORIES = [
  't-shirt',
  'blouse',
  'crop top',
  'tank top',
  'shirt',
  'hoodie',
  'sweater',
  'cardigan',
  'jeans',
  'skirt',
  'shorts',
  'trousers',
  'leggings',
  'cargo pants',
  'sweatpants',
  'mini dress',
  'bodycon',
  'jacket',
  'blazer',
  'coat',
  'trench coat',
  'puffer',
  'leather jacket',
  'denim jacket',
  'vest',
  'sneakers',
  'heels',
  'boots',
  'sandals',
  'platforms',
  'bag',
  'belt',
  'hat',
  'sunglasses',
  'jewellery',
  'scarf',
  'watch',
  'handbag',
  'tote',
  'clutch',
  'backpack',
  'mini bag',
  'shoulder bag',
  'one-piece',
  'coverup',
  'swim shorts',
];

const ALLOWED_GARMENT_STYLE_TAGS = [
  'formal',
  'casual',
  'sportswear',
  'streetwear',
  'business',
  'loungewear',
  'evening',
  'outdoor',
  'workwear',
  'vacation',
  'athleisure',
  'vintage',
  'minimalist',
  'luxury',
  'seasonal',
];

const ALLOWED_GARMENT_SUBCATEGORY_SET = new Set(ALLOWED_GARMENT_SUBCATEGORIES);
const ALLOWED_GARMENT_STYLE_TAG_SET = new Set(ALLOWED_GARMENT_STYLE_TAGS);

const ALLOWED_FABRICS = [
  'cotton',
  'denim',
  'leather',
  'silk',
  'wool',
  'polyester',
  'linen',
  'velvet',
  'chiffon',
  'fleece',
  'lace',
  'nylon',
  'corduroy',
  'spandex',
  'satin'
];
const ALLOWED_FABRIC_SET = new Set(ALLOWED_FABRICS);

module.exports = {
  ALLOWED_GARMENT_SUBCATEGORIES,
  ALLOWED_GARMENT_STYLE_TAGS,
  ALLOWED_GARMENT_SUBCATEGORY_SET,
  ALLOWED_GARMENT_STYLE_TAG_SET,
  ALLOWED_FABRICS,
  ALLOWED_FABRIC_SET,
};
