const DEFAULT_MAX_MB = 5;
const DEFAULT_MAX_DIMENSION_PX = 6000;
const DEFAULT_MAX_MEGAPIXELS = 25;
const DEFAULT_ORPHAN_RETENTION_DAYS = 30;

const parsePositiveNumber = (value, fallback) => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return fallback;
  }
  return parsed;
};

const IMAGE_UPLOAD_MAX_MB = parsePositiveNumber(process.env.IMAGE_UPLOAD_MAX_MB, DEFAULT_MAX_MB);
const IMAGE_UPLOAD_MAX_BYTES = Math.round(IMAGE_UPLOAD_MAX_MB * 1024 * 1024);
const IMAGE_UPLOAD_MAX_LABEL = `${IMAGE_UPLOAD_MAX_MB}MB`;
const IMAGE_UPLOAD_MAX_DIMENSION_PX = Math.round(parsePositiveNumber(process.env.IMAGE_UPLOAD_MAX_DIMENSION_PX, DEFAULT_MAX_DIMENSION_PX));
const IMAGE_UPLOAD_MAX_MEGAPIXELS = parsePositiveNumber(process.env.IMAGE_UPLOAD_MAX_MEGAPIXELS, DEFAULT_MAX_MEGAPIXELS);
const IMAGE_UPLOAD_MAX_PIXELS = Math.round(IMAGE_UPLOAD_MAX_MEGAPIXELS * 1000000);
const ORPHAN_UPLOAD_RETENTION_DAYS = Math.round(parsePositiveNumber(process.env.ORPHAN_UPLOAD_RETENTION_DAYS, DEFAULT_ORPHAN_RETENTION_DAYS));

module.exports = {
  IMAGE_UPLOAD_MAX_MB,
  IMAGE_UPLOAD_MAX_BYTES,
  IMAGE_UPLOAD_MAX_LABEL,
  IMAGE_UPLOAD_MAX_DIMENSION_PX,
  IMAGE_UPLOAD_MAX_MEGAPIXELS,
  IMAGE_UPLOAD_MAX_PIXELS,
  ORPHAN_UPLOAD_RETENTION_DAYS,
};
