import { Dimensions, Platform, StyleSheet } from "react-native";

const { width: W } = Dimensions.get("window");
const PINK = "#e83d84";

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#fff" },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "android" ? 16 : 8,
    paddingBottom: 4,
  },
  topBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  imageWrap: {
    marginHorizontal: 18,
    borderRadius: 20,
    overflow: "hidden",
    height: 320,
    backgroundColor: "#f0eeea",
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  imagePlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  cpwPill: {
    position: "absolute",
    bottom: 48,
    backgroundColor: PINK,
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 48,
  },
  cpwText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "500",
  },
  imageActions: {
    position: "absolute",
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  tabNav: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    marginTop: 14,
  },
  tabBtn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    position: "relative",
  },
  tabBtnText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#aaa",
  },
  tabBtnTextActive: {
    color: "#111",
    fontWeight: "700",
  },
  tabUnderline: {
    position: "absolute",
    bottom: 0,
    left: "20%",
    right: "20%",
    height: 2,
    backgroundColor: "#111",
    borderRadius: 2,
  },
  content: {
    flex: 1,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 8,
  },
  rowLabel: {
    fontSize: 15,
    fontWeight: "500",
    color: "#1a1a1a",
  },
  divider: {
    height: 1,
    backgroundColor: "#f0f0f0",
    marginHorizontal: 20,
  },
  categoryPill: {
    backgroundColor: "#f5f5f5",
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  categoryText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#333",
    letterSpacing: 0.5,
  },
  swatches: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  swatch: {
    width: 34,
    height: 34,
    borderRadius: 17,
  },
  swatchBorder: {
    borderWidth: 1,
    borderColor: "#ddd",
  },
  swatchSelected: {
    borderWidth: 3,
    borderColor: PINK,
  },
  colorPicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  addBtn: {
    borderWidth: 1,
    borderColor: PINK,
    borderRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 16,
  },
  addBtnText: {
    color: PINK,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  inlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  inlineInput: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 13,
    color: "#1a1a1a",
    width: 120,
  },
  inlineSave: {
    backgroundColor: PINK,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  inlineSaveText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
  },
  tagsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 20,
    paddingBottom: 12,
    alignItems: "center",
  },
  tagPill: {
    backgroundColor: PINK,
    borderRadius: 20,
    paddingVertical: 6,
    paddingLeft: 14,
    paddingRight: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  tagText: {
    color: "#fff",
    fontSize: 13,
  },
  tagX: {
    color: "#fff",
    fontSize: 18,
    lineHeight: 20,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statCard: {
    width: (W - 64) / 2,
    backgroundColor: "#fafafa",
    borderWidth: 1,
    borderColor: "#f0f0f0",
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
  },
  statVal: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  statLbl: {
    fontSize: 12,
    color: "#aaa",
    marginTop: 4,
    fontWeight: "500",
  },
  emptyState: {
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 40,
    gap: 10,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#1a1a1a",
  },
  emptySubtitle: {
    fontSize: 13,
    color: "#aaa",
    textAlign: "center",
    marginBottom: 8,
  },
  pinkBtn: {
    backgroundColor: PINK,
    borderRadius: 30,
    paddingVertical: 13,
    paddingHorizontal: 32,
    alignItems: "center",
  },
  pinkBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "500",
  },
});
